Fix to run-runner, added help to top level build

diff --git a/bin/run-runner b/bin/run-runner
--- a/bin/run-runner
+++ b/bin/run-runner
@@ -6,8 +6,11 @@
 # You can watch the logs with  docker logs ml-run-$$ -f 
 # If attached then a control-C or other signal will gracefully shutdown
 name=${1:?"Usage: $0 runner-name [network]"}
-network=${2:-${DOCKER_NETWORK:?"Usage: $0 runner-name [network or \$DOCKER_NETWORK]"}}
 shift
+network=${1:-${DOCKER_NETWORK:?"Usage: $0 runner-name [network or \$DOCKER_NETWORK]"}}
+[ $# -gt 0 ]  && shift 
+
+image=ml-runner
 
 # Check if there is an IP listed for name
 
@@ -23,8 +26,8 @@ ip=$(findip $name )
 [ -n "$ip" ]  && setip="--ip=$ip"
 
 echo "Starting ml-runner: $name"
-docker run -itd "--net=$network" $setip -P -v /dev/log:/dev/log --name=$name \
-   --hostname=$name -e MARKLOGIC_HOSTNAME=$name ml-runner "$@" || { echo "Error starting runner:$?" ; exit 1; }
+docker run -itd "--net=$network" $setip -v /dev/log:/dev/log --name=$name \
+   --hostname=$name -e MARKLOGIC_HOSTNAME=$name  -P "$@" "$image" || { echo "Error starting runner:$?" ; exit 1; }
 
 echo -n "Started runner on ip: "
 docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $name 
