Improved tagging and naming of ml-runner, Pass through the hostname to MarkLogic so it doesnt pick up on any local host domain or search set in /etc/hosts

diff --git a/bin/run-runner b/bin/run-runner
--- a/bin/run-runner
+++ b/bin/run-runner
@@ -5,13 +5,26 @@
 # You can find the addres with 'docker inspect ml-run-xxx 
 # You can watch the logs with  docker logs ml-run-$$ -f 
 # If attached then a control-C or other signal will gracefully shutdown
-name=${1:-ml-run-$$}
+name=${1:?"Usage: $0 runner-name [network]"}
+network=${2:-${DOCKER_NETWORK:?"Usage: $0 runner-name [network or \$DOCKER_NETWORK]"}}
 shift
 
+# Check if there is an IP listed for name
+
+findip() {
+  if which resolveip >/dev/null 2>&1 ; then 
+     resolveip -s $1
+  elif which getent >/dev/null 2>&1 ; then 
+     getent host $1 | awk '{ print $1 ; }'
+   fi
+}
+
+ip=$(findip $name )
+[ -n "$ip" ]  && setip="--ip=$ip"
+
 echo "Starting ml-runner: $name"
-docker run -itd --net=ml-docker -P -v /dev/log:/dev/log --name=$name \
-   --hostname=$name ml-runner "$@" || { echo "Error starting runner:$?" ; exit 1; }
+docker run -itd "--net=$network" $setip -P -v /dev/log:/dev/log --name=$name \
+   --hostname=$name -e MARKLOGIC_HOSTNAME=$name ml-runner "$@" || { echo "Error starting runner:$?" ; exit 1; }
 
 echo -n "Started runner on ip: "
-echo -n "IP Address: " 
 docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $name 
